spring:
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:~/test
        driver-Class-Name: org.h2.Driver
        username: sa
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    sql:
        init:
            encoding: UTF-8
            mode: always

mybatis:
    mapper-locations: mapper/**/*.xml
    type-aliases-package: com.koscom.demo.protocol # resultType의 package명을 생략해도 되는 곳 설정
    configuration:
        map-underscore-to-camel-case: true # DB 필드의 '_' 형식을 Camel Case로 변경